
title:       <h3><font color="#fff9e6">April 22, 7pm <br><br>Why Domain Knowledge is Crucial for Machine Learning-based Medical Image Analysis<br><br>Lena Maier-Hein, DKFZ</font></h3>
author:
email:
description:
author:
baseurl:
url:               "https://heidelbergai.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username:

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

future: true
