title:             <font size="medium" color="#fff9e6">heidelberg.ai</font>
email:             
description:       <h3><font color="#fff9e6">May 15, 7pm, Parameter Space Noise for Exploration (Matthias Plappert, OpenAI)</font></h3>
author:            
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

future: true
