
title:       <h3><font color="#fff9e6">March 24, 7pm <br><br>Immersions - Visualizing and sonifying how an Artificial Ear hears music<br><br>Vincent Herrmann, University of Music Karlsruhe</font></h3>
author:
email:
description:
author:
baseurl:
url:               "https://heidelbergai.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username:

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

future: true
