
title:       <h3><font color="#fff9e6">May 6, 11am <br><br>Learning Equivariant and Hybrid Message Passing on Graphs<br><br>Max Welling, University of Amsterdam</font></h3>
author:
email:
description:
author:
baseurl:
url:               "https://heidelbergai.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username:

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

future: true
